export const formConfig = {
  modalWidth: "max-w-4xl",
  fields: [
    {
      name: "motor_tariff_type_id",
      label: "Motor Tariff Type",
      type: "select",
      required: true,
      endpoint: "/v1/motor-tariff-types",
      responseKey: "data",
      labelKey: "name",
      valueKey: "id",
      isSearchable: true,
      placeholder: "Select Tariff Type",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "motor_tariff_group_id",
      label: "Motor Tariff Group",
      type: "select",
      required: true,
      endpoint: "/v1/motor-tariff-groups",
      responseKey: "data",
      labelKey: "name",
      valueKey: "id",
      isSearchable: true,
      placeholder: "Select Tariff Group",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "motor_class_sub_type_id",
      label: "Class Sub Type",
      type: "select",
      required: true,
      endpoint: "/v1/motor-class-sub-types",
      responseKey: "data",
      labelKey: "name",
      valueKey: "id",
      isSearchable: true,
      placeholder: "Select Class Sub Type",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "motor_vehicle_usage_id",
      label: "Vehicle Usage",
      type: "select",
      required: true,
      endpoint: "/v1/motor-vehicle-usages",
      responseKey: "data",
      labelKey: "name",
      valueKey: "id",
      isSearchable: true,
      placeholder: "Select Vehicle Usage",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "tname",
      label: "Tariff Name / Description",
      type: "text",
      required: true,
      placeholder: "e.g. Up to 1,300 CC, Below 5 tons",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "capacity_type",
      label: "Capacity Type",
      type: "select",
      options: [
        { label: "Cubic Capacity (CC)", value: "cc" },
        { label: "Tonnage (Ton)", value: "ton" },
        { label: "Seat Capacity", value: "seat" },
        { label: "Trailer Count", value: "trailer_count" },
        { label: "None", value: "none" },
      ],
      placeholder: "Select Capacity Type",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "capacity_from",
      label: "Capacity From",
      type: "number",
      placeholder: "e.g. 0",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "capacity_to",
      label: "Capacity To",
      type: "number",
      placeholder: "e.g. 1300",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "own_dp_basic",
      label: "Basic Own Damage Premium (Tk)",
      type: "number",
      placeholder: "e.g. 2795",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "full_ins_value",
      label: "Full Insured Value Rate (%)",
      type: "number",
      placeholder: "e.g. 2.65",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "act_liability",
      label: "Act Liability Premium (Tk)",
      type: "number",
      placeholder: "e.g. 750",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "driver_rate",
      label: "Driver Premium Rate (Tk)",
      type: "number",
      placeholder: "e.g. 150",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "passenger_rate",
      label: "Passenger Premium Rate (Tk)",
      type: "number",
      placeholder: "e.g. 225",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "helper_rate",
      label: "Helper Premium Rate (Tk)",
      type: "number",
      placeholder: "e.g. 150",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "fire_rate",
      label: "Fire Rate (%)",
      type: "number",
      placeholder: "e.g. 0.5",
      colSpan: "col-span-12 md:col-span-4",
    },
    {
      name: "theft_rate",
      label: "Theft Rate (%)",
      type: "number",
      placeholder: "e.g. 0.5",
      colSpan: "col-span-12 md:col-span-4",
    },
  ],
};
