export const formFieldsConfig = [
  {
    name: "motor_tariff_type_id",
    label: "Motor Tariff Type",
    type: "select",
    required: true,
    endpoint: "/v1/motor-tariff-types",
    responseKey: "data",
    labelKey: "name",
    valueKey: "id",
    isSearchable: true,
    placeholder: "Select Motor Tariff Type",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "name",
    label: "Tariff Group Name",
    type: "text",
    required: true,
    placeholder: "e.g. Private Vehicle, Commercial Class A(1)",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "description",
    label: "Description",
    type: "textarea",
    required: false,
    placeholder: "Enter optional description for tariff group...",
    colSpan: "col-span-12",
  },
];
