export const formFieldsConfig = [
  {
    name: "policy_type_id",
    label: "Policy Type",
    type: "select",
    required: true,
    endpoint: "/v1/omp-policy-types",
    mappingTemplate: "ompPolicyTypeTemplate",
    responseKey: "data",
    labelKey: "label",
    valueKey: "id",
    isSearchable: true,
    placeholder: "Select Policy Type",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "plan_option_id",
    label: "Plan Option",
    type: "select",
    required: true,
    endpoint: "/v1/omp-plan-options",
    mappingTemplate: "ompPlanOptionTemplate",
    responseKey: "data",
    labelKey: "label",
    valueKey: "id",
    isSearchable: true,
    placeholder: "All / None",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "min_days",
    label: "Minimum Days",
    type: "number",
    placeholder: "e.g. 1",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "max_days",
    label: "Maximum Days",
    type: "number",
    placeholder: "e.g. 14",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "min_age",
    label: "Minimum Age",
    type: "number",
    placeholder: "e.g. 0",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "max_age",
    label: "Maximum Age",
    type: "number",
    placeholder: "e.g. 80",
    colSpan: "col-span-12 md:col-span-6",
  },
  {
    name: "is_schengen",
    label: "Schengen Tariff",
    type: "select",
    required: true,
    options: [
      { label: "Non-Schengen", value: false },
      { label: "Schengen", value: true },
    ],
    colSpan: "col-span-12",
  },
  {
    name: "rates",
    label: "Tariff Rates (Key & Value Repeater)",
    type: "group",
    colSpan: "col-span-12",
    children: [
      {
        name: "key",
        label: "Key ",
        type: "text",
        placeholder: "e.g. G1",
        required: true,
        colSpan: "col-span-12 md:col-span-6",
      },
      {
        name: "value",
        label: "Rate Amount",
        type: "number",
        placeholder: "e.g. 1500",
        required: true,
        colSpan: "col-span-12 md:col-span-6",
      },
    ],
  },
];
